#!/usr/bin/env node

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { tiledToTemplate, validateTemplate } from './tiledImport.mjs';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const MAPS_DIR = path.join(ROOT, 'maps');
const OUT_FILE = path.join(ROOT, 'src/data/tiledMaps.generated.js');

function listTiledMapFiles() {
    if (!existsSync(MAPS_DIR)) return [];
    return readdirSync(MAPS_DIR)
        .filter((name) => name.endsWith('.json') && !name.endsWith('.template.json'))
        .filter((name) => name !== 'aliens_tileset.png')
        .sort();
}

function loadTemplateFromTiledFile(filename) {
    const abs = path.join(MAPS_DIR, filename);
    const raw = JSON.parse(readFileSync(abs, 'utf8'));
    const template = tiledToTemplate(raw);
    const validation = validateTemplate(template);
    return { filename, template, validation };
}

function toModuleSource(templates) {
    const header = [
        '// AUTO-GENERATED by scripts/generateTiledMapsModule.mjs',
        '// Do not edit manually. Edit maps/*.json in Tiled and regenerate.',
        '',
    ].join('\n');

    // Standard pretty-print first
    let json = JSON.stringify(templates, null, 4);

    // Collapse numeric arrays (like terrain rows) to single lines.
    // Matches: [ \n 1, \n 2 \n ] -> [1, 2]
    // We use a loop to handle nested arrays correctly if needed, though specific regex for inner arrays works best.
    // This regex targets arrays containing only numbers, commas, whitespace, and negative signs.
    json = json.replace(/\[\s*([\d,\s-]+?)\s*\]/g, (match, content) => {
        // limit replacement to likely numeric arrays (not mixed types) to be safe
        if (/[^\d,\s-]/.test(content)) return match;
        return '[' + content.replace(/\s+/g, ' ').trim() + ']';
    });

    return `${header}export const TILED_MAP_TEMPLATES = Object.freeze(${json});\n`;
}

function main() {
    const files = listTiledMapFiles();
    const templates = [];

    for (const file of files) {
        const { template, validation } = loadTemplateFromTiledFile(file);
        if (!validation.valid) {
            const msg = validation.warnings.join('; ');
            throw new Error(`Invalid Tiled map ${file}: ${msg}`);
        }
        templates.push(template);
    }

    mkdirSync(path.dirname(OUT_FILE), { recursive: true });
    writeFileSync(OUT_FILE, toModuleSource(templates));
    console.log(`Generated ${OUT_FILE} from ${templates.length} Tiled map(s).`);
}

main();
