export const CONFIG = Object.freeze({
    // Display
    GAME_WIDTH: 1280,
    GAME_HEIGHT: 720,

    // Tile
    TILE_SIZE: 64,

    // Map dimensions (in tiles)
    MAP_WIDTH_TILES: 40,
    MAP_HEIGHT_TILES: 26,

    // Tile indices
    TILE_FLOOR: 0,
    TILE_WALL: 1,

    // Team Leader
    LEADER_SPEED: 180,
    LEADER_SIZE: 40,
    LEADER_COLOR: 0x3366ff,
    MARINE_FOLLOWER_SPEED: 220,
    MARINE_FOLLOWER_LERP: 0.1,
    MARINE_REACTION_DELAY_MS: 90,
    SQUAD_SIZE: 4,

    // Bullet pool
    BULLET_POOL_SIZE: 80,

    // Player health
    PLAYER_MAX_HEALTH: 100,
    PLAYER_START_HEALTH: 100,

    // HUD layout
    HUD_HEIGHT: 168,
    HUD_BG_COLOR: 0x111111,
    HUD_BG_ALPHA: 0.85,
    HUD_WEAPON_SLOT_WIDTH: 100,
    HUD_WEAPON_SLOT_HEIGHT: 60,
    HUD_HEALTH_BAR_WIDTH: 150,
    HUD_HEALTH_BAR_HEIGHT: 16,
    HUD_HEAT_BAR_WIDTH: 100,
    HUD_HEAT_BAR_HEIGHT: 10,

    // Heat colors
    HEAT_COLOR_NORMAL: 0xffaa00,
    HEAT_COLOR_OVERHEAT: 0xff2200,
    HEAT_COLOR_BG: 0x333333,

    // Health colors
    HEALTH_COLOR_HIGH: 0x44cc44,
    HEALTH_COLOR_MED: 0xcccc44,
    HEALTH_COLOR_LOW: 0xcc4444,
    HEALTH_COLOR_BG: 0x333333,

    // Weapon slot colors
    WEAPON_SLOT_BG: 0x222233,
    WEAPON_SLOT_SELECTED: 0x3344aa,
    WEAPON_SLOT_BORDER: 0x666688,
    WEAPON_SLOT_EMPTY: 0x444444,

    // Weapon icon size
    WEAPON_ICON_SIZE: 40,

    // Camera
    CAMERA_LERP: 0.1,
    CAMERA_DEADZONE_WIDTH: 50,
    CAMERA_DEADZONE_HEIGHT: 50,

    // Pathfinding
    DIAGONAL_COST: 1.414,
    CARDINAL_COST: 1.0,
    PATH_TURN_PENALTY: 0.06,
    PATH_ARRIVAL_THRESHOLD: 4,
    PATHFINDING_SMOOTHING_ENABLED: true,
    PATH_LOOKAHEAD_DIST: 18,
    MOVE_RESPONSE_RATE: 9.5,

    // Placeholder tile colors
    FLOOR_COLOR: 0x333333,
    WALL_COLOR: 0x886644,

    // Door colors
    DOOR_COLOR_CLOSED: 0xcc4444,
    DOOR_COLOR_OPEN: 0x44aa44,
    DOOR_BORDER_CLOSED: 0x882222,
    DOOR_BORDER_OPEN: 0x228822,
    DOOR_COLOR_LOCKED: 0xccaa44,
    DOOR_BORDER_LOCKED: 0x886622,
    DOOR_COLOR_WELDED: 0x6688aa,
    DOOR_BORDER_WELDED: 0x445566,
    DOOR_WELD_MARK: 0xaaccee,

    // Door action durations (ms)
    DOOR_HACK_DURATION: 3000,
    DOOR_LOCK_DURATION: 3000,
    DOOR_WELD_DURATION: 4000,
    DOOR_UNWELD_DURATION: 3000,

    // Torch / Lighting
    TORCH_RANGE: 470,
    TORCH_CONE_HALF_ANGLE: 0.65,
    AMBIENT_DARKNESS: 0.5,
    LIGHTING_DEPTH: 190,
    TORCH_RAY_EPSILON: 0.0001,
    TORCH_NEARBY_TILE_RADIUS: 9,
    MARINE_LIGHT_SOFT_RADIUS: 150,
    TORCH_FILL_RAY_SPACING: 26,
    TORCH_FILL_RAY_MIN: 18,
    TORCH_FILL_RAY_MAX: 72,
    TORCH_FEATHER_LAYERS: 8,
    TORCH_FEATHER_ANGLE_STEP: 0.09,
    TORCH_FEATHER_RANGE_STEP: 0.12,
    TORCH_CORE_ALPHA: 0.55,
    TORCH_FEATHER_ALPHA_DECAY: 0.52,
    TORCH_SOFT_GLOW_STEPS: 12,
    TORCH_SOFT_GLOW_ALPHA: 0.65,
    TORCH_FOG_HALO_RADIUS_FACTOR: 3.6,
    TORCH_FOG_HALO_ALPHA: 0.28,
    LIGHT_SOURCE_VIEW_RADIUS: 720,
    LIGHT_SHADER_EFFECT_RANGE: 420,
    LIGHTING_ADAPTIVE_SHADOW_MIN_ALPHA: 0.45,
    LIGHTING_ADAPTIVE_SHADOW_FPS_RANGE: 36,

    // Enemy detection
    DETECTION_FADE_ALPHA: 0.18,
    DETECTION_LABEL_DEPTH: 120,
    SPOTTED_MEMORY_MS: 2000,

    // Motion tracker
    MOTION_TRACKER_RANGE: 1472, // 23 tiles × 64px — matches MotionTracker.js cone range
    MOTION_TRACKER_SIZE: 150,
    MOTION_TRACKER_DEPTH: 230,
    MOTION_TRACKER_SCAN_MS: 10000,
    MOTION_TRACKER_RISK_MS: 10000,
    MOTION_TRACKER_COOLDOWN_MS: 30000,
});
